# Generated by Django 5.1.3 on 2024-12-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField()),
                ('stadium', models.CharField(max_length=100)),
                ('foundation_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
